---
- name: Docker Container Deployment
  hosts: target_machine
  become: yes

  tasks:
    - name: Install pip package manager
      apt:
        name: python3-pip
        state: present

    - name: Install Docker Python module
      pip:
        name: docker
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Create Docker network
      docker_network:
        name: my_network
        subnet: 172.168.10.0/30

    - name: Pull latest Apache image and expose port 80
      docker_container:
        name: apache_container
        image: httpd
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - /path/to/html:/usr/local/apache2/htdocs
        networks:
          - name: my_network

    - name: Transfer HTML file to target machine
      copy:
        src: /path/to/html/file.html
        dest: /path/to/destination/directory/file.html